---
kind: wasmer.io/App.v0
name: wasmer-python-flask-server-starter
package: wasmer/python-flask-starter
cli_args:
  - -m
  - flask
  - --app
  - /src/main
  - run
  - --debug
  - --no-reload
env:
  PYTHONEXECUTABLE: /bin/python
