[package]
name = "wasmer-examples/flask-wasmer-starter"
version = "0.2.0"
description = "Flask Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/flask-wasmer-starter"

[dependencies]
"wasmer/python" = "^3.12.6"

[fs]
"/src" = "./src"
"/cpython/lib/python3.12" = "./.env/lib/python3.9"

[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = [
    "-m",
    "flask",
    "--app",
    "/src/main",
    "run",
    "--debug",
    "--no-reload",
]
env = ["PYTHONEXECUTABLE=/bin/python"]
